//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATO
    {
        public decimal ID_CONTRATO { get; set; }
        public System.DateTime FECHA_INI { get; set; }
        public System.DateTime FECHA_FIN { get; set; }
        public string ANEXO_PDF { get; set; }
        public decimal PERSONA_RUT { get; set; }
    
        public virtual PERSONA PERSONA { get; set; }
    }
}
