//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFERTA_VENTA
    {
        public OFERTA_VENTA()
        {
            this.DETALLE_OFERTA = new HashSet<DETALLE_OFERTA>();
            this.PRODUCTO_OFERTA = new HashSet<PRODUCTO_OFERTA>();
        }
    
        public decimal ID_OFERTA { get; set; }
        public decimal COSTO { get; set; }
        public string CALIDAD_FRUTA_CALIDAD { get; set; }
        public decimal PERSONA_RUT { get; set; }
    
        public virtual CALIDAD_FRUTA CALIDAD_FRUTA { get; set; }
        public virtual ICollection<DETALLE_OFERTA> DETALLE_OFERTA { get; set; }
        public virtual PERSONA PERSONA { get; set; }
        public virtual ICollection<PRODUCTO_OFERTA> PRODUCTO_OFERTA { get; set; }
    }
}
