//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONA
    {
        public PERSONA()
        {
            this.CONTRATO = new HashSet<CONTRATO>();
            this.OFERTA_SUBASTA = new HashSet<OFERTA_SUBASTA>();
            this.OFERTA_VENTA = new HashSet<OFERTA_VENTA>();
        }
    
        public decimal RUT { get; set; }
        public string RUT_DV { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public string EMAIL { get; set; }
        public decimal PERFIL_ID_PERFIL { get; set; }
    
        public virtual ICollection<CONTRATO> CONTRATO { get; set; }
        public virtual LOGIN LOGIN { get; set; }
        public virtual ICollection<OFERTA_SUBASTA> OFERTA_SUBASTA { get; set; }
        public virtual ICollection<OFERTA_VENTA> OFERTA_VENTA { get; set; }
        public virtual PERFIL PERFIL { get; set; }
    }
}
