//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBASTA_TRANSPORTE
    {
        public SUBASTA_TRANSPORTE()
        {
            this.OFERTA_SUBASTA = new HashSet<OFERTA_SUBASTA>();
            this.VENTA = new HashSet<VENTA>();
        }
    
        public decimal ID_SUBASTA { get; set; }
        public System.DateTime FECHA_INI { get; set; }
        public System.DateTime FECHA_FIN { get; set; }
        public decimal CAPACIDAD_CARGA { get; set; }
        public decimal TAMANO_CARGA { get; set; }
        public string REFRIGERACION { get; set; }
        public string ESTADO { get; set; }
    
        public virtual ICollection<OFERTA_SUBASTA> OFERTA_SUBASTA { get; set; }
        public virtual ICollection<VENTA> VENTA { get; set; }
    }
}
