//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUSBASTA
    {
        public SUSBASTA()
        {
            this.OFERTA_SUSBASTA = new HashSet<OFERTA_SUSBASTA>();
        }
    
        public decimal ID_SUBASTA { get; set; }
        public System.DateTime FECHA_INI { get; set; }
        public System.DateTime FECHA_FIN { get; set; }
    
        public virtual ICollection<OFERTA_SUSBASTA> OFERTA_SUSBASTA { get; set; }
    }
}
