//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTA
    {
        public decimal ID_VENTA { get; set; }
        public System.DateTime FECHA { get; set; }
        public decimal TOTAL { get; set; }
        public decimal TIPO_VENTA_ID_TIPO_VENTA { get; set; }
        public decimal PROCESO_VENTA_ID_PROCESO { get; set; }
        public decimal SEGURO_VENTA_ID_SEGURO { get; set; }
        public decimal SUBASTA_TRANSPORTE_ID_SUBASTA { get; set; }
    
        public virtual DETALLE_VENTA DETALLE_VENTA { get; set; }
        public virtual PROCESO_VENTA PROCESO_VENTA { get; set; }
        public virtual SEGURO_VENTA SEGURO_VENTA { get; set; }
        public virtual SUBASTA_TRANSPORTE SUBASTA_TRANSPORTE { get; set; }
        public virtual TIPO_VENTA TIPO_VENTA { get; set; }
    }
}
