//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CALIDAD_FRUTA> CALIDAD_FRUTA { get; set; }
        public DbSet<CONTRATO> CONTRATO { get; set; }
        public DbSet<DETALLE_VENTA> DETALLE_VENTA { get; set; }
        public DbSet<LOGIN> LOGIN { get; set; }
        public DbSet<OFERTA_PROCESO_VENTA> OFERTA_PROCESO_VENTA { get; set; }
        public DbSet<OFERTA_SUSBASTA> OFERTA_SUSBASTA { get; set; }
        public DbSet<PERFIL> PERFIL { get; set; }
        public DbSet<PERSONA> PERSONA { get; set; }
        public DbSet<PROCESO_VENTA> PROCESO_VENTA { get; set; }
        public DbSet<PRODUCTO> PRODUCTO { get; set; }
        public DbSet<SEGURO_VENTA> SEGURO_VENTA { get; set; }
        public DbSet<SUSBASTA> SUSBASTA { get; set; }
        public DbSet<TIPO_SEGURO> TIPO_SEGURO { get; set; }
        public DbSet<TIPO_VENTA> TIPO_VENTA { get; set; }
        public DbSet<VENTA> VENTA { get; set; }
        public DbSet<PRODUCTO_PROCESO> PRODUCTO_PROCESO { get; set; }
    }
}
