//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGIN
    {
        public string PASSWORD { get; set; }
        public string ESTADO { get; set; }
        public decimal PERSONA_RUT { get; set; }
    
        public virtual PERSONA PERSONA { get; set; }
    }
}
