//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFERTA_PROCESO_VENTA
    {
        public decimal ID { get; set; }
        public decimal COSTO { get; set; }
        public decimal STOCK { get; set; }
        public string CALIDAD_FRUTA_CALIDAD { get; set; }
        public decimal PROCESO_VENTA_ID { get; set; }
        public decimal PERSONA_RUT { get; set; }
    
        public virtual CALIDAD_FRUTA CALIDAD_FRUTA { get; set; }
        public virtual PERSONA PERSONA { get; set; }
        public virtual PROCESO_VENTA PROCESO_VENTA { get; set; }
    }
}
