//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROCESO_VENTA
    {
        public PROCESO_VENTA()
        {
            this.OFERTA_PROCESO_VENTA = new HashSet<OFERTA_PROCESO_VENTA>();
            this.VENTA = new HashSet<VENTA>();
        }
    
        public decimal ID { get; set; }
        public System.DateTime FECHA_INI { get; set; }
        public System.DateTime FECHA_FIN { get; set; }
    
        public virtual ICollection<OFERTA_PROCESO_VENTA> OFERTA_PROCESO_VENTA { get; set; }
        public virtual ICollection<VENTA> VENTA { get; set; }
    }
}
