//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO_PROCESO
    {
        public decimal PRODUCTO_ID { get; set; }
        public decimal OFERTA_PROCESO_VENTA_ID { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
