//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEGURO_VENTA
    {
        public SEGURO_VENTA()
        {
            this.VENTA = new HashSet<VENTA>();
        }
    
        public decimal ID_SEGURO { get; set; }
        public string ASEGURADORA { get; set; }
        public decimal VALOR { get; set; }
        public decimal TIPO_SEGURO_ID { get; set; }
    
        public virtual TIPO_SEGURO TIPO_SEGURO { get; set; }
        public virtual ICollection<VENTA> VENTA { get; set; }
    }
}
